version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0 # Specify your .NET version here
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore backend/DataCollector/DataCollector.csproj

  build:
    commands:
      - echo Build started on `date`
      - dotnet build backend/DataCollector/DataCollector.csproj
  
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish backend/DataCollector/DataCollector.csproj -c Release -o ./publish
      - mkdir -p ./publish/data
      - rsync -av backend/DataCollector/data/ ./publish/data/ # Make sure to copy the full data folder

artifacts:
  files:
    - publish/** # All contents in the `publish` folder

# Optionally, specify your deployment location here, or rely on CodePipeline to handle it.