[tool.poetry]
name = "env"
version = "0.1.0"
description = ""
authors = ["elnukakujo <jagernoe1s3@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
